### ISSUE TITLE
how to get proxy path like this /api

### ISSUE THREAD

**Issue by TunLinAung010** [garutilorenzo/docker-swarm-ingress#12]
Hello, i would like to know how to enable proxy path like this www.example.com/api using this docker swarm-ingress?

please help me.

**Comment by garutilorenzo** [comment]
Have you read the doc?

```
docker service create --name my-service \
  --network ingress-routing \
  --label ingress.host=www.example.com \
  <your container image>
```

Then _your container image_ must expose /api context
