### ISSUE TITLE
Request: example of multiple services and their url's

### ISSUE THREAD

**Issue by cmarkle85** [garutilorenzo/docker-swarm-ingress#7]
Its not obvious to me how I would reach each service being handled by this ingress service. 

Example: If I create 2 services: api1 and api2
1. do I need to create 2 DNS entries:
  * 1 entry for each, each having its own Fully Qualified Domain Name and a unique IP address pointing to a different node in the swarm
2. do I need a single DNS entry:
  * services are reached at a subdomain or unique path

**Comment by garutilorenzo** [comment]
Hi @cmarkle85, this nginx ingress is exactly the same thing of having a simple nginx instance with multiple virtual hosts.
So if you create N services with their own FQDN you have to create N DNS entries.
For the second question, it depends on how you handle HA for your cluster:

1. You can create multiple A DNS entry for a single FQDN name, the entries are the public ip addresses of your docker swarm cluster. This is know as round robin DNS
2. Set a load balancer in front of the swarm cluster, and then create the A DNS entry with a single ip address (the load balancer address)
